theme = "hyde"
baseURL = "http://blog.guyhf.com.s3-website-us-west-1.amazonaws.com/"
languageCode = "en-us"
title = "Guy Haskin Fernald"
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]
[Params]
  logo = "/images/guyhf_headshot_900.jpg"
  resumeURL = "http://resume.guyhf.com"
  description = "I'm a Data Scientist at Vium, interested in using technology and data to understand and advance biology and medicine."